services:
  api:
    container_name: api
    image: gjeodnd12165/victory-fairy:alpine
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TCP_PORT=${DB_TCP_PORT}
      - REDIS_CONTAINER=${REDIS_CONTAINER}
      - REDIS_TCP_PORT=${REDIS_TCP_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PW=${MAIL_PW}
      - MAIL_FROM=${MAIL_FROM}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_EXPIRE_TIME=${ACCESS_EXPIRE_TIME}
      - REFRESH_EXPIRE_TIME=${REFRESH_EXPIRE_TIME}
      - BACK_END_URL=${BACK_END_URL}
      - FRONT_END_URL=${FRONT_END_URL}
  redis-server:
    container_name: ${REDIS_CONTAINER}
    image: redis:alpine
    ports:
      - '${REDIS_TCP_PORT}:${REDIS_TCP_PORT}'
    command: >
      redis-server
      --port ${REDIS_TCP_PORT}
      --requirepass ${REDIS_PASSWORD}
      --save ""
      --appendonly no
      --maxmemory 100mb
      --maxmemory-policy allkeys-lru
