services:
  api:
    container_name: api
    image: gjeodnd12165/victory-fairy:alpine
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TCP_PORT=${DB_TCP_PORT}
      - DB_MAX_CONNECTIONS=${DB_MAX_CONNECTIONS}
      - REDIS_CONTAINER=${REDIS_CONTAINER}
      - REDIS_TCP_PORT=${REDIS_TCP_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_SES_ACCESS_KEY=${AWS_SES_ACCESS_KEY}
      - AWS_SES_SECRET_ACCESS_KEY=${AWS_SES_SECRET_ACCESS_KEY}
      - AWS_SES_FROM_ADDRESS=${AWS_SES_FROM_ADDRESS}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_EXPIRE_TIME=${ACCESS_EXPIRE_TIME}
      - REFRESH_EXPIRE_TIME=${REFRESH_EXPIRE_TIME}
      - BACK_END_URL=${BACK_END_URL}
      - FRONT_END_URL=${FRONT_END_URL}
      - SWAGGER_USER=${SWAGGER_USER}
      - SWAGGER_PW=${SWAGGER_PW}
      - SERIES_ID=${SERIES_ID}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - DISCORD_REPORT_WEBHOOK=${DISCORD_REPORT_WEBHOOK}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - APPLE_SERVICE_ID=${APPLE_SERVICE_ID}
      - APPLE_TEAM_ID=${APPLE_TEAM_ID}
      - APPLE_KEY_ID=${APPLE_KEY_ID}
      - APPLE_PRIVATE_KEY_BASE64=${APPLE_PRIVATE_KEY_BASE64}
      - SENTRY_DSN=${SENTRY_DSN}

  redis-server:
    container_name: ${REDIS_CONTAINER}
    image: redis:alpine
    ports:
      - '${REDIS_TCP_PORT}:${REDIS_TCP_PORT}'
    command: >
      redis-server
      --port ${REDIS_TCP_PORT}
      --requirepass ${REDIS_PASSWORD}
      --save ""
      --appendonly no
      --maxmemory 100mb
      --maxmemory-policy allkeys-lru
