services:
  api:
    container_name: api
    image: gjeodnd12165/victory-fairy:alpine
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - DOMAIN=${DOMAIN}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TCP_PORT=${DB_TCP_PORT}
      - REDIS_CONTAINER=${REDIS_CONTAINER}
      - REDIS_TCP_PORT=${REDIS_TCP_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PW=${MAIL_PW}
      - MAIL_FROM=${MAIL_FROM}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_EXPIRE_TIME=${ACCESS_EXPIRE_TIME}
      - REFRESH_EXPIRE_TIME=${REFRESH_EXPIRE_TIME}
      - BACK_END_URL=${BACK_END_URL}
      - FRONT_END_URL=${FRONT_END_URL}
    volumes:
      - ./src:/usr/src/app/src
  postgres:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    ports:
      - '${DB_TCP_PORT}:${DB_TCP_PORT}'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
  redis-server:
    container_name: ${REDIS_CONTAINER}
    image: redis:alpine
    ports:
      - '${REDIS_TCP_PORT}:${REDIS_TCP_PORT}'
    command: redis-server --port ${REDIS_TCP_PORT} --requirepass ${REDIS_PASSWORD}
