import { HttpStatus } from '@nestjs/common';
import {
  REGISTERED_GAME_ERROR_CODE,
  RegisteredGameErrorCode,
} from 'src/modules/registered-game/core/domain/error/registered-game.error';
import {
  RANK_ERROR_CODE,
  RankErrorCode,
} from 'src/modules/rank/core/domain/error/rank.error';

export const DOMAIN_ERROR_HTTP_MAP: Record<
  RegisteredGameErrorCode | RankErrorCode,
  HttpStatus
> = {
  // RegisteredGameError
  [REGISTERED_GAME_ERROR_CODE.USER_REQUIRED]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.GAME_REQUIRED]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.CHEERING_TEAM_REQUIRED]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.SEAT_REQUIRED]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.REVIEW_REQUIRED]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.INVALID_CHEERING_TEAM]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.ALREADY_REGISTERED]: HttpStatus.CONFLICT,
  [REGISTERED_GAME_ERROR_CODE.NOT_FOUND]: HttpStatus.NOT_FOUND,
  // RankError
  [RANK_ERROR_CODE.RECORD_NOT_FOUND]: HttpStatus.BAD_REQUEST,
  [RANK_ERROR_CODE.INVALID_RECORD_DECREASE]: HttpStatus.BAD_REQUEST,
  [RANK_ERROR_CODE.INVALID_TEAM_ID]: HttpStatus.BAD_REQUEST,
  [RANK_ERROR_CODE.INVALID_USER_ID]: HttpStatus.BAD_REQUEST,
  [RANK_ERROR_CODE.INVALID_ACTIVE_YEAR]: HttpStatus.BAD_REQUEST,
};
