import { HttpStatus } from '@nestjs/common';
import {
  REGISTERED_GAME_ERROR_CODE,
  RegisteredGameErrorCode,
} from 'src/modules/registered-game/core/domain/error/registered-game.error';
import {
  RANK_ERROR_CODE,
  RankErrorCode,
} from 'src/modules/rank/core/domain/error/rank.error';
import {
  ACCOUNT_ERROR_CODE,
  AccountErrorCode,
} from 'src/modules/account/core/domain/error/account.error';

export const DOMAIN_ERROR_HTTP_MAP: Record<
  RegisteredGameErrorCode | RankErrorCode | AccountErrorCode,
  HttpStatus
> = {
  // RegisteredGameError
  [REGISTERED_GAME_ERROR_CODE.USER_REQUIRED]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.GAME_REQUIRED]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.CHEERING_TEAM_REQUIRED]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.SEAT_REQUIRED]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.REVIEW_REQUIRED]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.INVALID_CHEERING_TEAM]: HttpStatus.BAD_REQUEST,
  [REGISTERED_GAME_ERROR_CODE.ALREADY_REGISTERED]: HttpStatus.CONFLICT,
  [REGISTERED_GAME_ERROR_CODE.NOT_FOUND]: HttpStatus.NOT_FOUND,
  // RankError
  [RANK_ERROR_CODE.RECORD_NOT_FOUND]: HttpStatus.BAD_REQUEST,
  [RANK_ERROR_CODE.INVALID_RECORD_DECREASE]: HttpStatus.BAD_REQUEST,
  [RANK_ERROR_CODE.INVALID_TEAM_ID]: HttpStatus.BAD_REQUEST,
  [RANK_ERROR_CODE.INVALID_USER_ID]: HttpStatus.BAD_REQUEST,
  [RANK_ERROR_CODE.INVALID_ACTIVE_YEAR]: HttpStatus.BAD_REQUEST,
  // AccountError
  [ACCOUNT_ERROR_CODE.USER_NOT_FOUND]: HttpStatus.BAD_REQUEST,
  [ACCOUNT_ERROR_CODE.EMAIL_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [ACCOUNT_ERROR_CODE.INVALID_CREDENTIALS]: HttpStatus.UNAUTHORIZED,
  [ACCOUNT_ERROR_CODE.NICKNAME_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [ACCOUNT_ERROR_CODE.NICKNAME_GENERATION_FAILED]:
    HttpStatus.INTERNAL_SERVER_ERROR,
  [ACCOUNT_ERROR_CODE.NOT_LOCAL_ACCOUNT]: HttpStatus.BAD_REQUEST,
  [ACCOUNT_ERROR_CODE.INVALID_TEAM_ID]: HttpStatus.BAD_REQUEST,
  [ACCOUNT_ERROR_CODE.EMPTY_NICKNAME]: HttpStatus.BAD_REQUEST,
  [ACCOUNT_ERROR_CODE.EMPTY_PROFILE_IMAGE]: HttpStatus.BAD_REQUEST,
  [ACCOUNT_ERROR_CODE.ALREADY_REGISTERED]: HttpStatus.BAD_REQUEST,
  [ACCOUNT_ERROR_CODE.ALREADY_LINKED]: HttpStatus.CONFLICT,
  [ACCOUNT_ERROR_CODE.NO_SOCIAL_LINK_HISTORY]: HttpStatus.NOT_FOUND,
  [ACCOUNT_ERROR_CODE.NOT_FOUND_SOCIAL_PLATFORM]: HttpStatus.NOT_FOUND,
  [ACCOUNT_ERROR_CODE.PRIMARY_SOCIAL_CANNOT_UNLINK]: HttpStatus.BAD_REQUEST,
  [ACCOUNT_ERROR_CODE.INVALID_SOCIAL_AUTH_DATA]: HttpStatus.BAD_REQUEST,
  [ACCOUNT_ERROR_CODE.INVALID_PROVIDER]: HttpStatus.BAD_REQUEST,
  [ACCOUNT_ERROR_CODE.EMPTY_TERM_ID]: HttpStatus.INTERNAL_SERVER_ERROR,
};
