name: Docker Build and AWS EB Deploy

on:
  push:
    branches: [ main, chore/deploy-test ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6.3.0
      with:
        context: .
        file: Dockerfile.prod
        push: true
        tags: gjeodnd12165/victory-fairy:alpine
    
    - name: Install jq
      run: sudo apt-get install jq -y

    - name: Generate .ebextensions config
      run: |
        mkdir -p .ebextensions
        echo "option_settings:" > .ebextensions/env.config
        echo "  aws:elasticbeanstalk:application:environment:" >> .ebextensions/env.config
        echo '${{ toJson(secrets) }}' | jq 'to_entries | 
          map(select(.key | 
            test("^(AWS_EB|DOCKERHUB)") | not)) | 
          from_entries' |
        jq -r 'to_entries[] | "    \(.key): \"\(.value)\""' >> .ebextensions/env.config
        echo '${{ toJson(vars) }}' | jq 'to_entries | 
          map(select(.key | 
            test("^(AWS_EB|DOCKERHUB)") | not)) | 
          from_entries' |
        jq -r 'to_entries[] | "    \(.key): \"\(.value)\""' >> .ebextensions/env.config

    - name: Add DockerHub Auth Config
      run: |
        mkdir -p .ebextensions
        
        # Use GitHub Secrets directly in the content
        echo "Creating Docker Hub auth config"
        echo 'files:' > .ebextensions/dockerhub_auth.config
        echo '  "/root/.docker/config.json":' >> .ebextensions/dockerhub_auth.config
        echo '    mode: "000600"' >> .ebextensions/dockerhub_auth.config
        echo '    owner: root' >> .ebextensions/dockerhub_auth.config
        echo '    group: root' >> .ebextensions/dockerhub_auth.config
        echo '    content: |' >> .ebextensions/dockerhub_auth.config
        echo '      {' >> .ebextensions/dockerhub_auth.config
        echo '        "auths": {' >> .ebextensions/dockerhub_auth.config
        echo '          "https://index.docker.io/v1/": {' >> .ebextensions/dockerhub_auth.config
        
        # Add auth entry with base64 encoding
        echo '            "auth": "'$(echo -n "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | base64)'"' >> .ebextensions/dockerhub_auth.config

        echo '          }' >> .ebextensions/dockerhub_auth.config
        echo '        }' >> .ebextensions/dockerhub_auth.config
        echo '      }' >> .ebextensions/dockerhub_auth.config

    - name: Create deployment package
      run: |
        mv docker-compose.yml docker-compose.temp.yml
        mv docker-compose.prod.yml docker-compose.yml
        zip -r deploy.zip .ebextensions docker-compose.yml
   
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_EB_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_EB_SECRET_ACCESS_KEY }}
        version_label: "${{ github.run_number }}-${{ github.run_attempt }}-${{ github.sha }}"
        application_name: Sngyo
        environment_name: Sngyo
        region: ap-northeast-2
        deployment_package: deploy.zip
